title: blog
author: Axims
email: gday@axims.id.au
description: > # this means to ignore newlines until "baseurl:"
  Old fashioned tech blog based off the early 2000s nerdy blogs. 
  Includes topics like IRC, TF2, BF2, MP3s, learning Linux and 
  living within ADSL download caps.

# social links
github_username:  Axxims # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
